[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nginx", "nodejs_18", "yarn"]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs",
  "npm ci"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
